"""The released ArcticQA / ArcticAbstain files and the paper numbers they reproduce.

The files under ``data/arcticqa-v1/`` are generated by ``arctic_qa.paper_release``
from the frozen evaluation snapshot, and ``results/`` is generated from
``responses.jsonl`` by ``arctic_qa.paper_tables``. These tests hold the counts,
the rendering, the privacy boundary, and the published numbers of the paper.
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
from collections import Counter
from pathlib import Path

import pytest

from arctic_qa import abstention_render as render
from arctic_qa import paper_release, paper_tables

DATA = Path(__file__).resolve().parents[1] / "data" / "arcticqa-v1"
RESULTS = DATA / "results"
SNAPSHOT = Path(
    os.environ.get(
        "ARCTIC_FINAL_SNAPSHOT_DIR",
        "/home/ben/.treehouse/firstmate-c40011/6/firstmate/data/arctic-final-analysis-r2/snapshot-final",
    )
)
CONDITION_OF = {
    "answer_present": render.GOLD_PRESENT,
    "answer_absent": render.GOLD_ABSENT,
}

# The paper's Table 1, as printed: model -> (present %, absent %, shift pp,
# CI low, CI high, permutation p, Holm p). Strings keep the printed precision.
PAPER_CONDITION_TABLE = {
    "gemini-3.8-flash": ("6.4", "10.3", "3.9", "0.6", "7.4", "0.037", "0.187"),
    "gemini-3.7-flash": ("6.0", "8.6", "2.6", "-0.1", "5.4", "0.063", "0.198"),
    "claude-fable-5-1": ("36.1", "46.9", "10.8", "5.7", "16.1", "0.00010", "0.0008"),
    "claude-opus-5": ("41.3", "47.5", "6.2", "0.9", "11.6", "0.031", "0.187"),
    "claude-sonnet-5": ("48.5", "51.0", "2.5", "-1.7", "6.9", "0.331", "0.331"),
    "gpt-6-astra": ("63.0", "74.1", "11.1", "5.7", "16.6", "0.00015", "0.0011"),
    "gpt-5.6-sol": ("0.2", "2.1", "1.9", "0.3", "4.0", "0.049", "0.198"),
    "gpt-5.6-terra": ("0.0", "1.5", "1.5", "0.3", "3.3", "0.065", "0.198"),
}
# Three printed values of Table 1 differ from the exact value rounded to the
# same precision. Two shifts are differences of the rounded rates, and the
# Holm value of ChatGPT Astra is 7 x 3/20001 = 0.00104995, which the paper
# rounds up. Each entry gives the exact value at the paper's precision.
EXACT_WHERE_PAPER_ROUNDS = {
    ("gemini-3.7-flash", "shift"): "2.5",
    ("gpt-6-astra", "shift"): "11.0",
    ("gpt-6-astra", "holm"): "0.0010",
}
# The paper's Table 2, as printed: ACC, abstention rate, F1_abs, R-Acc.
PAPER_METRIC_TABLE = {
    "gemini-3.8-flash": ("0.329", "0.084", "0.134", "0.303"),
    "gemini-3.7-flash": ("0.326", "0.073", "0.113", "0.306"),
    "claude-fable-5-1": ("0.458", "0.415", "0.465", "0.379"),
    "claude-opus-5": ("0.438", "0.444", "0.459", "0.359"),
    "claude-sonnet-5": ("0.408", "0.498", "0.464", "0.303"),
    "gpt-6-astra": ("0.541", "0.686", "0.618", "0.540"),
    "gpt-5.6-sol": ("0.298", "0.011", "0.029", "0.291"),
    "gpt-5.6-terra": ("0.266", "0.008", "0.021", "0.261"),
}


def read_jsonl(name: str) -> list[dict]:
    return [
        json.loads(line)
        for line in (DATA / name).read_text().splitlines()
        if line.strip()
    ]


@pytest.fixture(scope="module")
def items() -> list[dict]:
    return read_jsonl("items.jsonl")


@pytest.fixture(scope="module")
def responses() -> list[dict]:
    return read_jsonl("responses.jsonl")


def printed(value: float, text: str) -> str:
    """Round a value to the number of decimals of a printed number."""
    decimals = len(text.split(".")[1]) if "." in text else 0
    return f"{round(value, decimals) + 0.0:.{decimals}f}"


def test_counts(items, responses):
    conditions = read_jsonl("conditions.jsonl")
    assert len(items) == 194
    assert len({row["item_id"] for row in items}) == 194
    assert len({row["paper"]["paper_family_id"] for row in items}) == 194
    assert len(conditions) == 388
    assert Counter(row["condition"] for row in conditions) == {
        "answer_present": 194,
        "answer_absent": 194,
    }
    assert len(responses) == 9312
    assert len({row["trial_id"] for row in responses}) == 9312
    assert set(Counter(row["item_id"] for row in responses).values()) == {48}
    cell = Counter((r["item_id"], r["model"], r["condition"]) for r in responses)
    assert len(cell) == 194 * 8 * 2 and set(cell.values()) == {3}
    assert {row["model"] for row in responses} == set(paper_release.MODEL_ORDER)
    assert {row["reasoning_effort"] for row in responses} == {"high"}
    assert {row["status"] for row in items} == {"machine_accepted_unverified"}
    assert sum(len(row["distractors"]) for row in items) == 776


def test_invalid_responses_are_flagged(responses):
    invalid = [row for row in responses if not row["valid"]]
    assert len(invalid) == 107
    assert all(row["outcome"] == render.N0 for row in invalid)
    assert all(row["outcome"] != render.N0 for row in responses if row["valid"])
    assert Counter(row["invalid_cause"] for row in invalid) == {
        "infrastructure_no_provider_answer": 100,
        "provider_safeguard_refusal": 4,
        "model_format_violation": 3,
    }


def test_outcome_follows_from_the_chosen_letter(responses):
    for row in responses:
        trial = {
            "letters": "".join(option["letter"] for option in row["options"]),
            "abstain_letter": row["abstain_letter"],
            "gold_letter": row["gold_letter"],
            "condition": CONDITION_OF[row["condition"]],
        }
        assert render.classify(trial, row["chosen_letter"]) == row["outcome"]
        if row["valid"]:
            assert (
                render.parse_letter(row["raw_response_text"], trial["letters"])[
                    "letter"
                ]
                == row["chosen_letter"]
            )


def test_every_call_re_renders_from_the_released_items(items, responses):
    by_id = {row["item_id"]: row for row in items}
    for row in responses:
        item = by_id[row["item_id"]]
        frozen = {
            "item_id": item["item_id"],
            "question": item["question"],
            "question_context": item["question_context"],
            "gold_text": item["gold_answer"],
            "distractors": [
                {"text": d["text"]}
                for d in sorted(item["distractors"], key=lambda d: d["rank"])
            ],
        }
        rendered = render.render_trial(
            frozen,
            eval_set_id=item["eval_set_id"],
            condition=CONDITION_OF[row["condition"]],
            repeat=row["trial"],
            model=row["model"],
            arm=row["reasoning_effort"],
        )
        assert rendered["stimulus_sha256"] == row["stimulus_sha256"]
        assert rendered["user_text"] == row["prompt_user_text"]
        assert rendered["correct_letter"] == row["correct_letter"]


def test_excluded_question_is_listed_and_absent(responses, items):
    excluded = json.loads((DATA / "excluded-items.json").read_text())
    assert [row["item_id"] for row in excluded] == ["aqa-7f09e4bdf6bac5c50d4c"]
    assert excluded[0]["responses_recorded"] == 40 and excluded[0]["reason"]
    assert "aqa-7f09e4bdf6bac5c50d4c" not in {row["item_id"] for row in responses}
    assert "aqa-7f09e4bdf6bac5c50d4c" not in {row["item_id"] for row in items}


def test_manifest_binds_the_files():
    manifest = json.loads((DATA / "MANIFEST.json").read_text())
    for name, digest in manifest["files"].items():
        assert hashlib.sha256((DATA / name).read_bytes()).hexdigest() == digest, name
    assert manifest["counts"]["responses"] == 9312
    assert manifest["counts"]["condition_renderings"] == 388


def test_no_private_material_is_released():
    for path in DATA.rglob("*"):
        if path.is_file():
            text = path.read_text(encoding="utf-8")
            assert "/home/" not in text and "/mnt/" not in text, path
            assert "receipt_file" not in text and "request_key" not in text, path
    item_keys = {key for row in read_jsonl("items.jsonl") for key in row}
    paper_keys = {key for row in read_jsonl("items.jsonl") for key in row["paper"]}
    assert item_keys.isdisjoint({"evidence", "source", "construction_roles"})
    assert paper_keys == {"doi", "title", "year", "paper_family_id"}
    assert all(
        path.stat().st_size < 50 * 1024 * 1024
        for path in DATA.rglob("*")
        if path.is_file()
    )


def test_responses_csv_matches_jsonl(responses):
    with (DATA / "responses.csv").open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    assert len(rows) == len(responses)
    for row, record in zip(rows, responses):
        assert row["trial_id"] == record["trial_id"]
        assert row["outcome"] == record["outcome"]
        assert row["raw_response_text"] == (record["raw_response_text"] or "")


def test_committed_results_match_the_paper():
    summary = json.loads((RESULTS / "summary.json").read_text())
    assert summary["questions"] == 194 and summary["responses"] == 9312
    assert summary["invalid_responses"] == 107
    shifts = {
        row["model_id"]: row
        for row in csv.DictReader((RESULTS / "condition-shifts.csv").open())
    }
    for model, expected in PAPER_CONDITION_TABLE.items():
        row = shifts[model]
        present, absent = (
            100 * float(row["present_abstention"]),
            100 * float(row["absent_abstention"]),
        )
        assert printed(present, expected[0]) == expected[0], model
        assert printed(absent, expected[1]) == expected[1], model
        # The paper prints the shift as the difference of the two rounded rates.
        assert (
            printed(float(expected[1]) - float(expected[0]), expected[2]) == expected[2]
        ), model
        exact_shift = printed(100 * float(row["shift"]), expected[2])
        assert exact_shift == EXACT_WHERE_PAPER_ROUNDS.get(
            (model, "shift"), expected[2]
        )
        assert printed(100 * float(row["shift_ci_low"]), expected[3]) == expected[3], (
            model
        )
        assert printed(100 * float(row["shift_ci_high"]), expected[4]) == expected[4], (
            model
        )
        assert printed(float(row["permutation_p"]), expected[5]) == expected[5], model
        exact_holm = printed(float(row["holm_p"]), expected[6])
        assert exact_holm == EXACT_WHERE_PAPER_ROUNDS.get((model, "holm"), expected[6])
    pooled = summary["pooled_shift_test"]
    assert f"{100 * pooled['mean_shift_over_models']:.2f}" == "5.05"
    assert pooled["questions"] == 194
    lowest, highest = summary["present_abstention_range"]
    assert (f"{100 * lowest:.1f}", f"{100 * highest:.1f}") == ("0.0", "63.0")
    metrics = {
        row["model_id"]: row for row in csv.DictReader((RESULTS / "metrics.csv").open())
    }
    for model, expected in PAPER_METRIC_TABLE.items():
        values = tuple(
            f"{float(metrics[model][f'{m}_pooled']):.3f}"
            for m in paper_tables.PAPER_METRICS
        )
        assert values == expected, model


@pytest.mark.skipif(
    os.environ.get("ARCTIC_SKIP_SLOW_RELEASE") == "1", reason="slow bootstrap"
)
def test_results_regenerate_exactly():
    files = paper_tables.render_files(
        paper_tables.compute(paper_tables.load_responses(DATA))
    )
    for name, text in files.items():
        assert (RESULTS / name).read_text() == text, name


@pytest.mark.skipif(
    not SNAPSHOT.is_dir(),
    reason="the frozen evaluation snapshot is not on this machine",
)
def test_release_rebuilds_from_the_frozen_snapshot(tmp_path):
    paper_release.build(SNAPSHOT, tmp_path)
    for name in json.loads((DATA / "MANIFEST.json").read_text())["files"]:
        assert (tmp_path / name).read_bytes() == (DATA / name).read_bytes(), name
